# manconv
# Autogenerated from man page /nix/store/nx7wng9729d9fgays4n2yc21kv71rbc6-man-db-2.11.2/share/man/man1/manconv.1.gz
complete -c manconv -s f -l from-code -d 'Try each of  encodings (a colon-separated list) in sequence as the input enco…'
complete -c manconv -s t -l to-code -d 'Convert the manual page to R encoding '
complete -c manconv -s q -l quiet -d 'Do not issue error messages when the page cannot be converted'
complete -c manconv -s d -l debug -d 'Print debugging information'
complete -c manconv -s h -l help -d 'Print a help message and exit'
complete -c manconv -s V -l version -d 'Display version information'

