# unzipsfx
# Autogenerated from man page /nix/store/504g56hb9vmy2jwa8c4p1xcldy5vcr77-unzip-6.0/share/man/man1/unzipsfx.1.gz
complete -c unzipsfx -s j -s V -d 'following operating-system specific options:  -X (restore VMS owner/protectio…'

