# zsoelim
# Autogenerated from man page /nix/store/nx7wng9729d9fgays4n2yc21kv71rbc6-man-db-2.11.2/share/man/man1/zsoelim.1.gz
complete -c zsoelim -s C -l compatible -d 'This flag is available for compatibility with other  soelim programs'
complete -c zsoelim -s h -l help -d 'Print a help message and exit'
complete -c zsoelim -s V -l version -d 'Display version information'

